"""Seed the Superstore star-schema dimension/bridge tables for the demo source.

The live-DirectQuery / DirectLake demo binds against a single flat ``dbo.Orders``
table (the Superstore union produced by ``_onboard_twbx.py``). The canonical
multi-source demo workbook additionally relates:

    Orders.[Region]   -> People.[Region]     (regional manager dimension)
    Orders.[Order ID] -> Returns.[Order ID]  (returned-orders bridge)

This tool derives ``dbo.People`` and ``dbo.Returns`` *from the rows already in*
``dbo.Orders`` so every foreign key resolves. It is:

  * Idempotent      -- safe to re-run; converges to the same deterministic state.
  * Transactional   -- any failure rolls the whole thing back; Orders is never touched.
  * Injection-safe  -- the T-SQL is a fixed template with constant identifiers and a
                       constant Region->Manager mapping; no value is ever concatenated in.

Because the demo Azure SQL server keeps ``publicNetworkAccess=Disabled`` (policy
``DenyPublicEndpointEnabled``), a direct connection from a workstation usually times
out. This script therefore ALWAYS writes a portable ``.sql`` you can paste into the
Fabric / portal query editor, and *additionally* executes it live when the server
happens to be reachable.

Auth (live path only): Microsoft Entra access token via an existing ``az login``
session -- no SQL password is ever used or stored.

Usage:
    py -3.11 _seed_star.py                       # write scripts/seed-star.sql + try live
    py -3.11 _seed_star.py --emit-only           # just write the .sql, never connect
    py -3.11 _seed_star.py --server <fqdn> --database <db> --sql-out path\\seed.sql
"""
from __future__ import annotations

import argparse
import os
import shutil
import struct
import subprocess
import sys

SQL_COPT_SS_ACCESS_TOKEN = 1256  # pyodbc access-token connection attribute
DEFAULT_SERVER = os.environ.get("TABMIG_SERVER", "sql-tabmig-ysh95n.database.windows.net")
DEFAULT_DB = os.environ.get("TABMIG_DB", "tabmigdb")
DEFAULT_SQL_OUT = os.path.join("scripts", "seed-star.sql")

# ---------------------------------------------------------------------------
# The complete server-side seeding batch. Every identifier and the Region->
# Manager mapping are constant literals, so there is no SQL-injection surface.
# ---------------------------------------------------------------------------
STAR_SQL = r"""-- seed-star.sql  (generated by _seed_star.py)
-- Derives dbo.People and dbo.Returns from the existing dbo.Orders rows so the
-- Superstore star-schema demo has referentially-consistent related tables.
--
--   Orders.[Region]   -> People.[Region]     (Region -> Regional Manager)
--   Orders.[Order ID] -> Returns.[Order ID]  (deterministic ~20% returned)
--
-- Idempotent + transactional. Never modifies dbo.Orders.

SET XACT_ABORT ON;
SET NOCOUNT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.Orders', 'U') IS NULL
        THROW 50001, 'dbo.Orders not found. Run the Orders onboarding first.', 1;
    IF COL_LENGTH('dbo.Orders', 'Order ID') IS NULL
        THROW 50002, 'dbo.Orders is missing the [Order ID] column.', 1;
    IF COL_LENGTH('dbo.Orders', 'Region') IS NULL
        THROW 50003, 'dbo.Orders is missing the [Region] column.', 1;

    ---------------------------------------------------------------------
    -- dbo.People : one row per Region present in Orders (Region -> Manager).
    ---------------------------------------------------------------------
    IF OBJECT_ID('dbo.People', 'U') IS NULL
        CREATE TABLE dbo.People (
            [Region]           NVARCHAR(100) NOT NULL
                CONSTRAINT PK_People_Region PRIMARY KEY,
            [Regional Manager] NVARCHAR(255) NOT NULL
        );

    TRUNCATE TABLE dbo.People;

    INSERT INTO dbo.People ([Region], [Regional Manager])
    SELECT r.[Region], COALESCE(m.[Manager], N'Unassigned')
    FROM (SELECT DISTINCT [Region] FROM dbo.Orders WHERE [Region] IS NOT NULL) AS r
    LEFT JOIN (VALUES
        (N'Central', N'Roxanne Rodriguez'),
        (N'East',    N'Chuck Magee'),
        (N'South',   N'Fred Suzuki'),
        (N'West',    N'Sadie Pawthorne')
    ) AS m([Region], [Manager]) ON m.[Region] = r.[Region];

    ---------------------------------------------------------------------
    -- dbo.Returns : deterministic ~20% of distinct Order IDs, all 'Yes'.
    ---------------------------------------------------------------------
    IF OBJECT_ID('dbo.Returns', 'U') IS NULL
        CREATE TABLE dbo.Returns (
            [Order ID] NVARCHAR(255) NOT NULL
                CONSTRAINT PK_Returns_OrderID PRIMARY KEY,
            [Returned] NVARCHAR(3) NOT NULL
                CONSTRAINT CK_Returns_Returned CHECK ([Returned] IN (N'Yes', N'No'))
        );

    TRUNCATE TABLE dbo.Returns;

    INSERT INTO dbo.Returns ([Order ID], [Returned])
    SELECT o.[Order ID], N'Yes'
    FROM (SELECT DISTINCT [Order ID] FROM dbo.Orders WHERE [Order ID] IS NOT NULL) AS o
    WHERE ABS(CAST(CHECKSUM(o.[Order ID]) AS BIGINT)) % 5 = 0;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;

SELECT N'People'  AS [Table], COUNT(*) AS [Rows] FROM dbo.People
UNION ALL
SELECT N'Returns' AS [Table], COUNT(*)          FROM dbo.Returns;
"""


def write_sql(path: str) -> None:
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(STAR_SQL)
    print(f"Wrote portable seeding script -> {path}")


def _entra_token_struct() -> bytes:
    az = shutil.which("az") or shutil.which("az.cmd")
    if not az:
        raise RuntimeError("az CLI not found on PATH; run 'az login' first.")
    raw = subprocess.check_output(
        [az, "account", "get-access-token", "--resource",
         "https://database.windows.net/", "--query", "accessToken", "-o", "tsv"],
        timeout=60,
    ).decode().strip()
    tok = raw.encode("utf-16-le")
    return struct.pack(f"<I{len(tok)}s", len(tok), tok)


def execute_live(server: str, database: str) -> bool:
    """Run the batch against Azure SQL. Returns True on success, False if unreachable."""
    try:
        import pyodbc
    except ImportError:
        print("pyodbc not installed for this interpreter -- skipping live execution.\n"
              "  Install with: py -3.11 -m pip install pyodbc")
        return False

    conn_str = (
        "Driver={ODBC Driver 18 for SQL Server};"
        f"Server={server},1433;Database={database};"
        "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
    )
    try:
        token = _entra_token_struct()
        cn = pyodbc.connect(conn_str, attrs_before={SQL_COPT_SS_ACCESS_TOKEN: token})
    except Exception as exc:  # noqa: BLE001 -- surface any connect failure as "unreachable"
        print(f"Live connection to {server} failed ({type(exc).__name__}). "
              "Server is likely private (publicNetworkAccess=Disabled).")
        return False

    try:
        cur = cn.cursor()
        cur.execute(STAR_SQL)
        # Advance to the trailing SELECT result set.
        while cur.description is None and cur.nextset():
            pass
        if cur.description is not None:
            for name, count in cur.fetchall():
                print(f"  seeded dbo.{name}: {count} rows")
        cn.commit()
        cur.close()
        return True
    finally:
        cn.close()


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--server", default=DEFAULT_SERVER,
                    help=f"Azure SQL FQDN (default: {DEFAULT_SERVER})")
    ap.add_argument("--database", default=DEFAULT_DB,
                    help=f"Database name (default: {DEFAULT_DB})")
    ap.add_argument("--sql-out", default=DEFAULT_SQL_OUT,
                    help=f"Path for the portable .sql (default: {DEFAULT_SQL_OUT})")
    ap.add_argument("--emit-only", action="store_true",
                    help="Only write the .sql; never attempt a live connection.")
    args = ap.parse_args(argv)

    write_sql(args.sql_out)

    if args.emit_only:
        return 0

    print(f"Attempting live execution against {args.server} / {args.database} ...")
    if execute_live(args.server, args.database):
        print("Live seeding complete.")
        return 0

    print(f"\nCould not seed live. Open the Fabric / portal query editor for "
          f"'{args.database}' and run:\n    {args.sql_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
