#!/usr/bin/env python3
"""Profile a published Tableau datasource via the Tableau REST + Metadata + VizQL Data Service APIs.

Read-only. Two API paths:
  * Metadata API (GraphQL, POST /api/metadata/graphql) -> schema/catalog/lineage. Default. No VDS rate limit.
  * VizQL Data Service (POST /api/v1/vizql-data-service/...) -> actual value stats. Optional (--with-stats).

Auth is direct REST; no tableauserverclient dependency, so it works against Tableau Cloud
and Server alike. Two modes (PAT default, Connected App Direct-Trust JWT opt-in via --auth jwt).
Credentials come from environment variables:
    TABLEAU_SERVER     e.g. https://10ax.online.tableau.com  (or your Server URL)
    TABLEAU_SITE       site contentUrl (the site's URL slug; "" for the Default site)
    TABLEAU_PAT_NAME   Personal Access Token name        (PAT auth)
    TABLEAU_PAT_VALUE  Personal Access Token secret      (PAT auth)
    TABLEAU_CONNECTED_APP_CLIENT_ID / _SECRET_ID / _SECRET_VALUE,
    TABLEAU_JWT_USERNAME                                 (JWT auth; --auth jwt)

Example:
    python profile_datasource.py --datasource-name "Superstore" --with-stats --format md
    python profile_datasource.py --datasource-luid abc-123 --format json --out profile.json
    python profile_datasource.py --datasource-name "Superstore" --dry-run
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import json
import math
import os
import sys
import time
import uuid
from typing import Any, Dict, List, Optional, Tuple

try:
    import requests
except ImportError:  # pragma: no cover - dependency guard
    requests = None  # Lazily required: --help and --dry-run work without it.


def _require_requests() -> None:
    if requests is None:
        sys.stderr.write(
            "ERROR: the 'requests' package is required for live calls. Install it with:\n"
            "    pip install -r requirements.txt\n"
        )
        raise SystemExit(2)


DEFAULT_REST_VERSION = "3.24"
NUMERIC_TYPES = {"INTEGER", "REAL"}
DATE_TYPES = {"DATE", "DATETIME"}


# --------------------------------------------------------------------------------------
# GraphQL: schema profile (Metadata API)
# --------------------------------------------------------------------------------------
# role/dataType are declared on the DataField interface; lineage (upstreamTables)
# on the base Field interface; formula on CalculatedField. See the metadata_api reference.
SCHEMA_GRAPHQL = """
query profile($luid: String!, $first: Int!, $after: String) {
  publishedDatasources(filter: {luid: $luid}) {
    id
    name
    luid
    projectName
    isCertified
    hasExtracts
    hasUserReference
    containsUnsupportedCustomSql
    description
    fieldsConnection(first: $first, after: $after) {
      totalCount
      pageInfo { hasNextPage endCursor }
      nodes {
        __typename
        name
        description
        isHidden
        folderName
        upstreamTables { name }
        ... on DataField { role dataType }
        ... on CalculatedField { formula isAutoGenerated hasUserReference }
        ... on ColumnField { columns { name } }
      }
    }
  }
}
""".strip()


class TableauError(RuntimeError):
    pass


# --------------------------------------------------------------------------------------
# Connected App (Direct Trust) JWT — built with the standard library (HS256), so no
# extra dependency is required. Structure verified against Tableau's official sign-in
# reference (rest_api_concepts_auth.htm): header {alg, kid, iss}; claims
# {aud:"tableau", sub, scp, iss, exp, jti}. Signed with the connected app secret value.
# --------------------------------------------------------------------------------------
# Tableau Pulse REST scopes (metric definitions/metrics, subscriptions, and the
# AI-powered insight bundle/brief endpoints).
PULSE_JWT_SCOPES = [
    "tableau:insight_definitions_metrics:read",
    "tableau:insight_metrics:read",
    "tableau:metric_subscriptions:read",
    "tableau:insights:read",
    "tableau:insight_brief:create",
]
# Core scopes the datasource tools (REST + Metadata + VDS) need. Kept minimal so they
# never depend on Pulse being licensed/enabled.
CORE_JWT_SCOPES = ["tableau:content:read", "tableau:viz_data_service:read"]
# Attempted by default: core + Pulse, so Pulse works out of the box. connect_from_env
# falls back to CORE_JWT_SCOPES if a site rejects the Pulse scopes at sign-in, so adding
# Pulse can never regress the datasource tools.
DEFAULT_JWT_SCOPES = [*CORE_JWT_SCOPES, *PULSE_JWT_SCOPES]
JWT_MAX_TTL_SECONDS = 600  # Tableau rejects connected-app JWTs with exp > ~10 minutes.


def _b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def build_connected_app_jwt(
    client_id: str,
    secret_id: str,
    secret_value: str,
    username: str,
    scopes: Optional[List[str]] = None,
    ttl_seconds: int = 300,
) -> str:
    """Build a signed HS256 JWT for Tableau Connected App (Direct Trust) sign-in.

    `client_id`  -> connected app Client ID (JWT `iss` + header context)
    `secret_id`  -> connected app Secret ID (JWT header `kid`)
    `secret_value` -> connected app Secret Value (HS256 signing key)
    `username`   -> the Tableau user to act as (JWT `sub`); enables impersonation.
    `scopes`     -> JWT-supported access scopes (JWT `scp`).
    """
    if not all([client_id, secret_id, secret_value, username]):
        raise TableauError(
            "JWT auth requires client_id, secret_id, secret_value, and username."
        )
    ttl = max(1, min(int(ttl_seconds), JWT_MAX_TTL_SECONDS))
    header = {"alg": "HS256", "kid": secret_id, "iss": client_id}
    now = int(time.time())
    payload = {
        "iss": client_id,
        "aud": "tableau",
        "sub": username,
        "scp": list(scopes) if scopes else list(DEFAULT_JWT_SCOPES),
        "exp": now + ttl,
        "jti": str(uuid.uuid4()),
    }
    signing_input = (
        _b64url(json.dumps(header, separators=(",", ":")).encode("utf-8"))
        + "."
        + _b64url(json.dumps(payload, separators=(",", ":")).encode("utf-8"))
    )
    signature = hmac.new(
        secret_value.encode("utf-8"), signing_input.encode("ascii"), hashlib.sha256
    ).digest()
    return signing_input + "." + _b64url(signature)


class VDSRateLimit(TableauError):
    """Raised on HTTP 429 from VDS (100 calls/hour per Creator exceeded)."""
    pass


class PulseUnavailable(TableauError):
    """Raised when Tableau Pulse (or its AI insights) is not enabled for the site."""
    pass


class TableauClient:
    """Minimal direct-REST Tableau client (Cloud + Server compatible)."""

    def __init__(self, server: str, site_content_url: str, rest_version: str) -> None:
        self.server = server.rstrip("/")
        self.site_content_url = site_content_url
        self.rest_version = rest_version
        self.token: Optional[str] = None
        self.site_id: Optional[str] = None
        self.vds_calls = 0
        # Set False if the site rejected the Pulse scopes at sign-in (Pulse tools then
        # report a clear "not enabled / scopes unavailable" error instead of failing raw).
        self.pulse_scopes_granted = True

    # -- auth ---------------------------------------------------------------------------
    @property
    def _rest_base(self) -> str:
        return f"{self.server}/api/{self.rest_version}"

    def _auth_headers(self) -> Dict[str, str]:
        if not self.token:
            raise TableauError("Not signed in.")
        return {
            "X-Tableau-Auth": self.token,
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    def sign_in(self, pat_name: str, pat_value: str) -> None:
        _require_requests()
        body = {
            "credentials": {
                "site": {"contentUrl": self.site_content_url},
                "personalAccessTokenName": pat_name,
                "personalAccessTokenSecret": pat_value,
            }
        }
        self._complete_signin(body)

    def sign_in_jwt(
        self,
        client_id: str,
        secret_id: str,
        secret_value: str,
        username: str,
        scopes: Optional[List[str]] = None,
    ) -> None:
        """Sign in via a Connected App (Direct Trust) JWT, acting as `username`."""
        _require_requests()
        jwt = build_connected_app_jwt(
            client_id, secret_id, secret_value, username, scopes
        )
        body = {
            "credentials": {
                "jwt": jwt,
                "site": {"contentUrl": self.site_content_url},
            }
        }
        self._complete_signin(body)

    def _complete_signin(self, body: Dict[str, Any]) -> None:
        resp = requests.post(
            f"{self._rest_base}/auth/signin",
            data=json.dumps(body),
            headers={"Content-Type": "application/json", "Accept": "application/json"},
            timeout=60,
        )
        if resp.status_code != 200:
            raise TableauError(f"Sign-in failed ({resp.status_code}): {resp.text[:500]}")
        try:
            creds = resp.json()["credentials"]
            self.token = creds["token"]
            self.site_id = creds["site"]["id"]
        except (ValueError, KeyError, TypeError):
            raise TableauError(f"Unexpected sign-in response: {resp.text[:500]}")

    def sign_out(self) -> None:
        if not self.token:
            return
        try:
            requests.post(
                f"{self._rest_base}/auth/signout",
                headers=self._auth_headers(),
                timeout=30,
            )
        finally:
            self.token = None
            self.site_id = None

    # -- datasource resolution ----------------------------------------------------------
    def list_datasources(self, page_size: int = 100) -> List[Dict[str, Any]]:
        """Return published datasources on the site as [{luid, name, project}], paged."""
        out: List[Dict[str, Any]] = []
        page = 1
        while True:
            url = f"{self._rest_base}/sites/{self.site_id}/datasources"
            params = {"pageSize": str(page_size), "pageNumber": str(page)}
            resp = requests.get(url, headers=self._auth_headers(), params=params, timeout=60)
            if resp.status_code != 200:
                raise TableauError(
                    f"List datasources failed ({resp.status_code}): {resp.text[:500]}"
                )
            body = resp.json()
            for d in body.get("datasources", {}).get("datasource", []):
                out.append({
                    "luid": d.get("id", ""),
                    "name": d.get("name", ""),
                    "project": (d.get("project") or {}).get("name", ""),
                })
            total = int(body.get("pagination", {}).get("totalAvailable", len(out)) or len(out))
            if page * page_size >= total or not body.get("datasources", {}).get("datasource"):
                break
            page += 1
        return out

    def resolve_datasource_luid(self, name: str) -> Tuple[str, str]:
        """Return (luid, name) for the published datasource matching `name`."""
        url = f"{self._rest_base}/sites/{self.site_id}/datasources"
        params = {"filter": f"name:eq:{name}", "pageSize": "100"}
        resp = requests.get(url, headers=self._auth_headers(), params=params, timeout=60)
        if resp.status_code != 200:
            raise TableauError(
                f"List datasources failed ({resp.status_code}): {resp.text[:500]}"
            )
        datasources = resp.json().get("datasources", {}).get("datasource", [])
        if not datasources:
            raise TableauError(f"No published datasource found named '{name}'.")
        if len(datasources) > 1:
            names = ", ".join(d.get("name", "?") for d in datasources)
            raise TableauError(
                f"Multiple datasources matched '{name}': {names}. Use --datasource-luid."
            )
        ds = datasources[0]
        return ds["id"], ds.get("name", name)

    # -- metadata api -------------------------------------------------------------------
    def metadata_query(self, query: str, variables: Dict[str, Any]) -> Dict[str, Any]:
        url = f"{self.server}/api/metadata/graphql"
        resp = requests.post(
            url,
            data=json.dumps({"query": query, "variables": variables}),
            headers=self._auth_headers(),
            timeout=120,
        )
        if resp.status_code != 200:
            raise TableauError(
                f"Metadata API failed ({resp.status_code}): {resp.text[:500]}"
            )
        payload = resp.json()
        if payload.get("errors"):
            raise TableauError(f"Metadata API errors: {json.dumps(payload['errors'])[:500]}")
        return payload["data"]

    # -- vizql data service -------------------------------------------------------------
    @property
    def _vds_base(self) -> str:
        return f"{self.server}/api/v1/vizql-data-service"

    def vds_read_metadata(self, luid: str) -> Optional[List[Dict[str, Any]]]:
        body = {"datasource": {"datasourceLuid": luid}}
        data = self._vds_post("/read-metadata", body)
        if data is None:
            return None
        return data.get("data", [])

    def vds_query(self, luid: str, query: Dict[str, Any],
                  options: Optional[Dict[str, Any]] = None) -> Optional[List[Dict[str, Any]]]:
        body: Dict[str, Any] = {"datasource": {"datasourceLuid": luid}, "query": query}
        if options:
            body["options"] = options
        data = self._vds_post("/query-datasource", body)
        if data is None:
            return None
        return data.get("data", [])

    def _vds_post(self, path: str, body: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        self.vds_calls += 1
        resp = requests.post(
            f"{self._vds_base}{path}",
            data=json.dumps(body),
            headers=self._auth_headers(),
            timeout=180,
        )
        if resp.status_code == 404:
            # VDS not enabled / Tableau < 2025.1 -> feature disabled.
            return None
        if resp.status_code == 429:
            raise VDSRateLimit(
                "VDS rate limit hit (429): 100 calls/hour per Creator exceeded."
            )
        if resp.status_code != 200:
            raise TableauError(
                f"VDS {path} failed ({resp.status_code}): {resp.text[:500]}"
            )
        try:
            payload = resp.json()
        except ValueError:
            raise TableauError(f"VDS {path} returned non-JSON: {resp.text[:500]}")
        # VDS can return HTTP 200 with an error envelope after partial streaming.
        if isinstance(payload, dict) and payload.get("error"):
            raise TableauError(f"VDS {path} error: {json.dumps(payload['error'])[:500]}")
        return payload

    # -- tableau pulse ------------------------------------------------------------------
    @property
    def _pulse_base(self) -> str:
        return f"{self.server}/api/-/pulse"

    @staticmethod
    def _pulse_insights_disabled(headers: Dict[str, str], text: str) -> bool:
        # These Tableau error codes mean AI-powered Pulse insights are disabled.
        codes = ("0x62c06627", "0x8c454877")
        blob = ((headers.get("tableau_error_code") or "") + " " + (text or "")).lower()
        return any(c in blob for c in codes)

    def _pulse_request(
        self,
        method: str,
        path: str,
        body: Optional[Dict[str, Any]] = None,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Call a Tableau Pulse REST endpoint, mapping 'disabled' states to PulseUnavailable."""
        _require_requests()
        url = f"{self._pulse_base}{path}"
        resp = requests.request(
            method.upper(),
            url,
            headers=self._auth_headers(),
            params=params,
            data=json.dumps(body) if body is not None else None,
            timeout=180,
        )
        headers = {k.lower(): v for k, v in resp.headers.items()}
        if resp.status_code == 404:
            raise PulseUnavailable(
                "Tableau Pulse is not available on this site (404). It requires Tableau "
                "Cloud with Pulse enabled."
            )
        if resp.status_code == 400 and headers.get("tableau_error_code") == "0xd3408984":
            raise PulseUnavailable("Tableau Pulse is disabled for this site.")
        if self._pulse_insights_disabled(headers, resp.text):
            raise PulseUnavailable(
                "Tableau Pulse AI insights are disabled for this site. Enable Pulse "
                "insights (AI features) in Tableau Cloud settings to use this tool."
            )
        if resp.status_code == 429:
            raise VDSRateLimit("Tableau Pulse rate limit hit (429).")
        if not (200 <= resp.status_code < 300):
            raise TableauError(
                f"Pulse {path} failed ({resp.status_code}): {resp.text[:500]}"
            )
        try:
            return resp.json()
        except ValueError:
            raise TableauError(f"Pulse {path} returned non-JSON: {resp.text[:500]}")

    def pulse_list_all_definitions(
        self, view: str = "DEFINITION_VIEW_DEFAULT", page_size: int = 100
    ) -> List[Dict[str, Any]]:
        """Return all published Pulse metric definitions (paged), each with its default metric."""
        out: List[Dict[str, Any]] = []
        page_token: Optional[str] = None
        while True:
            params: Dict[str, Any] = {"view": view, "page_size": str(page_size)}
            if page_token:
                params["page_token"] = page_token
            data = self._pulse_request("GET", "/definitions", params=params)
            out.extend(data.get("definitions", []) or [])
            page_token = data.get("next_page_token") or ""
            if not page_token:
                break
        return out

    def pulse_get_definition(
        self, definition_id: str, view: str = "DEFINITION_VIEW_DEFAULT"
    ) -> Optional[Dict[str, Any]]:
        """Return one Pulse metric definition (with its default metric) by definition ID."""
        data = self._pulse_request(
            "POST",
            "/definitions:batchGet",
            body={"definition_ids": [definition_id]},
            params={"view": view},
        )
        defs = data.get("definitions", []) or []
        return defs[0] if defs else None

    def pulse_resolve_metric(
        self, metric: str
    ) -> Tuple[Optional[Dict[str, Any]], Optional[Dict[str, Any]]]:
        """Resolve a metric name OR definition/metric ID to (definition, default_metric).

        Returns (None, None) if nothing matches. Matching is case-insensitive on the
        definition name; IDs are matched against the definition id, default metric id.
        """
        needle = (metric or "").strip()
        if not needle:
            return None, None
        definitions = self.pulse_list_all_definitions()
        lowered = needle.lower()
        for d in definitions:
            md = d.get("metadata", {}) or {}
            m = pulse_default_metric(d)
            metric_id = (m or {}).get("id", "")
            if (
                (md.get("name", "").lower() == lowered)
                or (md.get("id", "") == needle)
                or (metric_id and metric_id == needle)
            ):
                return d, m
        return None, None

    def pulse_generate_insight_bundle(
        self, bundle_request: Dict[str, Any], bundle_type: str = "ban"
    ) -> Dict[str, Any]:
        """POST a Pulse insight bundle request; bundle_type in ban|springboard|basic|detail."""
        return self._pulse_request(
            "POST", f"/insights/{bundle_type}", body=bundle_request
        )

    def pulse_generate_insight_brief(self, brief_request: Dict[str, Any]) -> Dict[str, Any]:
        """POST a Pulse insight-brief request (AI conversational answer about metrics)."""
        return self._pulse_request("POST", "/insights/brief", body=brief_request)

    def pulse_list_subscriptions(self, user_id: str) -> List[Dict[str, Any]]:
        """Return the current user's Pulse metric subscriptions."""
        data = self._pulse_request(
            "GET", "/subscriptions", params={"user_id": user_id}
        )
        return data.get("subscriptions", []) or []


# --------------------------------------------------------------------------------------
# Tableau Pulse payload assembly (server-side, so an agent only needs a metric name).
# The insight bundle/brief endpoints require the full metric definition + specification
# in the request body; we build those from a fetched definition + its default metric.
# --------------------------------------------------------------------------------------
def pulse_default_metric(definition: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Return the default metric embedded in a Pulse definition (view=DEFAULT/FULL)."""
    metrics = definition.get("metrics", []) or []
    for m in metrics:
        if m.get("is_default"):
            return m
    return metrics[0] if metrics else None


def assemble_pulse_bundle_request(
    definition: Dict[str, Any],
    metric: Dict[str, Any],
    output_format: str = "OUTPUT_FORMAT_HTML",
    time_zone: str = "UTC",
    language: str = "LANGUAGE_EN_US",
    locale: str = "LOCALE_EN_US",
) -> Dict[str, Any]:
    """Build the body for POST /pulse/insights/{bundle_type} from a definition + metric."""
    spec = definition.get("specification", {}) or {}
    md = definition.get("metadata", {}) or {}
    metric_input: Dict[str, Any] = {
        "definition": {
            "datasource": {"id": (spec.get("datasource", {}) or {}).get("id", "")},
            "basic_specification": spec.get("basic_specification", {}) or {},
            "is_running_total": bool(spec.get("is_running_total", False)),
        },
        "metric_specification": metric.get("specification", {}) or {},
        "extension_options": definition.get("extension_options", {}) or {},
        "representation_options": definition.get("representation_options", {}) or {},
        "insights_options": definition.get("insights_options", {}) or {},
    }
    if metric.get("goals"):
        metric_input["goals"] = metric["goals"]
    return {
        "bundle_request": {
            "version": 1,
            "options": {
                "output_format": output_format,
                "time_zone": time_zone,
                "language": language,
                "locale": locale,
            },
            "input": {
                "metadata": {
                    "name": md.get("name", ""),
                    "metric_id": metric.get("id", ""),
                    "definition_id": md.get("id", ""),
                },
                "metric": metric_input,
            },
        }
    }


def assemble_pulse_metric_group_context(
    definition: Dict[str, Any], metric: Dict[str, Any]
) -> Dict[str, Any]:
    """Build one metric_group_context entry for a Pulse insight-brief request."""
    spec = definition.get("specification", {}) or {}
    md = definition.get("metadata", {}) or {}
    ctx: Dict[str, Any] = {
        "metadata": {
            "name": md.get("name", ""),
            "metric_id": metric.get("id", ""),
            "definition_id": md.get("id", ""),
        },
        "metric": {
            "definition": spec,
            "metric_specification": metric.get("specification", {}) or {},
            "extension_options": definition.get("extension_options", {}) or {},
            "representation_options": definition.get("representation_options", {}) or {},
            "insights_options": definition.get("insights_options", {}) or {},
            "candidates": [],
        },
    }
    goals: Dict[str, Any] = {}
    if definition.get("datasource_goals"):
        goals["datasource_goals"] = definition["datasource_goals"]
    if metric.get("goals"):
        goals["metric_goals"] = metric["goals"]
    if goals:
        ctx["metric"]["goals"] = goals
    return ctx


# --------------------------------------------------------------------------------------
# Schema profiling
# --------------------------------------------------------------------------------------
def build_schema_profile(client: TableauClient, luid: str, page_size: int) -> Dict[str, Any]:
    header: Dict[str, Any] = {}
    fields: List[Dict[str, Any]] = []
    cursor: Optional[str] = None
    total: Optional[int] = None

    while True:
        data = client.metadata_query(
            SCHEMA_GRAPHQL, {"luid": luid, "first": page_size, "after": cursor}
        )
        dslist = data.get("publishedDatasources", [])
        if not dslist:
            raise TableauError(f"No published datasource found with luid '{luid}'.")
        ds = dslist[0]
        if not header:
            header = {
                "id": ds.get("id"),
                "name": ds.get("name"),
                "luid": ds.get("luid"),
                "projectName": ds.get("projectName"),
                "isCertified": ds.get("isCertified"),
                "hasExtracts": ds.get("hasExtracts"),
                "hasUserReference": ds.get("hasUserReference"),
                "containsUnsupportedCustomSql": ds.get("containsUnsupportedCustomSql"),
                "description": ds.get("description"),
            }
        conn = ds.get("fieldsConnection", {}) or {}
        total = conn.get("totalCount", total)
        for node in conn.get("nodes", []) or []:
            fields.append(_normalize_field(node))
        page_info = conn.get("pageInfo", {}) or {}
        if page_info.get("hasNextPage") and page_info.get("endCursor"):
            cursor = page_info["endCursor"]
        else:
            break

    return {"header": header, "fields": fields, "field_count": total if total is not None else len(fields)}


def _normalize_field(node: Dict[str, Any]) -> Dict[str, Any]:
    typename = node.get("__typename")
    is_calculated = typename == "CalculatedField"
    upstream_tables = [t.get("name") for t in node.get("upstreamTables", []) or [] if t.get("name")]
    referenced_columns = [c.get("name") for c in node.get("columns", []) or [] if c.get("name")]
    return {
        "name": node.get("name"),
        "typename": typename,
        "role": node.get("role"),
        "dataType": node.get("dataType"),
        "isHidden": node.get("isHidden"),
        "folderName": node.get("folderName"),
        "description": node.get("description"),
        "isCalculated": is_calculated,
        "formula": node.get("formula") if is_calculated else None,
        "isAutoGenerated": node.get("isAutoGenerated"),
        "upstreamTables": upstream_tables,
        "referencedColumns": referenced_columns,
    }


# --------------------------------------------------------------------------------------
# VDS value stats (optional, adaptive batching)
# --------------------------------------------------------------------------------------
# A valid VDS aggregate query returns exactly one row. Some fields cannot be aggregated
# the way we ask (bins and certain calcs 400; grouped fields are silently treated as a
# GROUP BY and return one row per member, corrupting every other field in the query). We
# therefore batch per function, and on a 400 *or* a multi-row response we split the batch
# and retry, isolating and dropping only the offending field(s).
def is_vds_aggregatable(field: Dict[str, Any]) -> bool:
    """Heuristic: skip fields VDS can't aggregate cleanly. Bins 400; grouped fields are
    silently treated as a GROUP BY. Both are detectable from the VDS fieldName suffix."""
    fname = (field.get("fieldName") or "").lower()
    return not (fname.endswith("(bin)") or "(group)" in fname or "(set)" in fname)


def build_agg_groups(vds_fields: List[Dict[str, Any]]) -> List[Tuple[str, str, List[str]]]:
    """Return (function, out_key, [captions]) groups for the stats we collect."""
    def caps(pred) -> List[str]:
        seen: Dict[str, None] = {}
        for f in vds_fields:
            c = f.get("fieldCaption")
            if c and pred(f.get("dataType")) and c not in seen:
                seen[c] = None
        return list(seen)

    numeric = caps(lambda t: t in NUMERIC_TYPES)
    dates = caps(lambda t: t in DATE_TYPES)
    dims = caps(lambda t: t not in NUMERIC_TYPES | DATE_TYPES)
    everything = caps(lambda t: True)

    groups = [
        ("COUNT", "non_null", everything),
        ("COUNTD", "cardinality", dims),
        ("MIN", "min", numeric),
        ("MAX", "max", numeric),
        ("AVG", "avg", numeric),
        ("MIN", "min_date", dates),
        ("MAX", "max_date", dates),
    ]
    return [g for g in groups if g[2]]


def estimate_vds_calls(vds_fields: List[Dict[str, Any]], max_fields: int) -> int:
    """Optimistic count: one read-metadata plus one query per full batch (no splits)."""
    groups = build_agg_groups(vds_fields)
    return 1 + sum(math.ceil(len(caps) / max_fields) for _, _, caps in groups)


def run_vds_stats(
    client: TableauClient, luid: str, max_fields: int, max_calls: int = 100
) -> Optional[Dict[str, Any]]:
    vds_fields = client.vds_read_metadata(luid)
    if vds_fields is None:
        return None  # feature disabled

    fields = [
        {
            "fieldCaption": f.get("fieldCaption"),
            "fieldName": f.get("fieldName"),
            "dataType": f.get("dataType"),
        }
        for f in vds_fields
        if f.get("fieldCaption")
    ]
    skipped_unaggregatable = [
        f["fieldCaption"] for f in fields if not is_vds_aggregatable(f)
    ]
    fields = [f for f in fields if is_vds_aggregatable(f)]

    estimated = estimate_vds_calls(fields, max_fields)
    if estimated > max_calls:
        return {
            "row_count": None,
            "fields": {},
            "vds_calls": client.vds_calls,
            "note": (
                f"Skipped VDS value stats: would need ~{estimated} calls, over the "
                f"{max_calls}/hr limit. Reduce field count or raise --max-fields-per-query."
            ),
        }

    stats: Dict[str, Dict[str, Any]] = {}
    warnings: List[str] = []
    budget = {"capped": False, "rate_limited": False, "stop": False}

    def run_chunk(function: str, out_key: str, caps: List[str]) -> None:
        if not caps or budget["stop"]:
            return
        if client.vds_calls >= max_calls:
            budget["capped"] = True
            budget["stop"] = True
            return
        body = {"fields": [
            {"fieldCaption": c, "function": function, "fieldAlias": f"a{i}"}
            for i, c in enumerate(caps)
        ]}
        try:
            rows = client.vds_query(luid, body)
        except VDSRateLimit:
            budget["rate_limited"] = True
            budget["stop"] = True
            return
        except TableauError as exc:
            if len(caps) == 1:
                warnings.append(f"{caps[0]} [{function}]: {str(exc)[:140]}")
                return
            mid = len(caps) // 2
            run_chunk(function, out_key, caps[:mid])
            run_chunk(function, out_key, caps[mid:])
            return
        if rows is None:
            return
        # Exactly one row == clean aggregate. More rows == a field acted as a GROUP BY.
        if len(rows) != 1:
            if len(caps) == 1:
                warnings.append(
                    f"{caps[0]} [{function}]: not aggregatable (returned {len(rows)} rows)"
                )
                return
            mid = len(caps) // 2
            run_chunk(function, out_key, caps[:mid])
            run_chunk(function, out_key, caps[mid:])
            return
        row = rows[0]
        for i, c in enumerate(caps):
            stats.setdefault(c, {})[out_key] = row.get(f"a{i}")

    for function, out_key, caps in build_agg_groups(fields):
        if budget["stop"]:
            break
        for i in range(0, len(caps), max_fields):
            run_chunk(function, out_key, caps[i : i + max_fields])

    # Row count is approximated as the max non-null count across fields (>= any single
    # non-null count), so null_count is never negative. VDS has no COUNT(*).
    non_nulls = {
        c: v["non_null"] for c, v in stats.items()
        if isinstance(v.get("non_null"), (int, float))
    }
    row_count = max(non_nulls.values()) if non_nulls else None
    if row_count:
        for c, nn in non_nulls.items():
            stats[c]["null_count"] = row_count - nn
            stats[c]["null_rate"] = round((row_count - nn) / row_count, 4)

    result: Dict[str, Any] = {
        "row_count": row_count,
        "row_count_approx": True,
        "fields": stats,
        "vds_calls": client.vds_calls,
    }
    notes: List[str] = []
    if budget["rate_limited"]:
        notes.append(
            "Stopped early: VDS returned 429 (100 calls/hour per Creator). "
            "Stats shown are partial; retry later."
        )
    if budget["capped"]:
        notes.append(f"Hit the {max_calls}-call VDS budget; some stats were skipped.")
    if skipped_unaggregatable:
        notes.append(
            f"{len(skipped_unaggregatable)} bin/group/set field(s) excluded from value "
            f"stats (not aggregatable in VDS): {', '.join(skipped_unaggregatable[:5])}"
            + ("…" if len(skipped_unaggregatable) > 5 else "")
        )
    if warnings:
        notes.append(
            f"{len(warnings)} field/aggregation combo(s) skipped as not aggregatable "
            f"(e.g. calculated measures). First: {warnings[0]}"
        )
    if notes:
        result["note"] = " ".join(notes)
    return result


# --------------------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------------------
def render_json(profile: Dict[str, Any]) -> str:
    return json.dumps(profile, indent=2, default=str)


def render_markdown(profile: Dict[str, Any]) -> str:
    header = profile["schema"]["header"]
    fields = profile["schema"]["fields"]
    stats = (profile.get("stats") or {}).get("fields") or {}
    row_count = (profile.get("stats") or {}).get("row_count")

    calc_count = sum(1 for f in fields if f.get("isCalculated"))
    measure_count = sum(1 for f in fields if (f.get("role") or "").lower() == "measure")
    dim_count = sum(1 for f in fields if (f.get("role") or "").lower() == "dimension")
    hidden_count = sum(1 for f in fields if f.get("isHidden"))

    lines: List[str] = []
    lines.append(f"# Datasource Profile: {header.get('name')}")
    lines.append("")
    lines.append(f"- **Project:** {header.get('projectName')}")
    lines.append(f"- **LUID:** {header.get('luid')}")
    lines.append(f"- **Certified:** {header.get('isCertified')}")
    lines.append(f"- **Has extracts:** {header.get('hasExtracts')}")
    lines.append(f"- **Contains unsupported custom SQL:** {header.get('containsUnsupportedCustomSql')}")
    lines.append(f"- **Has user reference (RLS/USERNAME):** {header.get('hasUserReference')}")
    if header.get("description"):
        lines.append(f"- **Description:** {header.get('description')}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total fields: {profile['schema'].get('field_count')}")
    lines.append(f"- Measures: {measure_count} | Dimensions: {dim_count} | Hidden: {hidden_count}")
    lines.append(f"- Calculated fields (DAX translation needed): **{calc_count}**")
    if row_count is not None:
        approx = " (approx; max non-null across fields)" if profile.get("stats", {}).get("row_count_approx") else ""
        lines.append(f"- Row count{approx}: {row_count}")
    lines.append("")

    has_stats = bool(stats)
    lines.append("## Fields")
    lines.append("")
    if has_stats:
        lines.append("| Field | Role | Type | Calc? | Cardinality | Null rate | Min | Max | Avg |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
    else:
        lines.append("| Field | Role | Type | Calc? | Hidden | Folder |")
        lines.append("|---|---|---|---|---|---|")

    for f in fields:
        name = f.get("name") or ""
        role = f.get("role") or ""
        dtype = f.get("dataType") or ""
        calc = "yes" if f.get("isCalculated") else ""
        if has_stats:
            s = stats.get(name, {})
            lines.append(
                f"| {name} | {role} | {dtype} | {calc} | {_fmt(s.get('cardinality'))} "
                f"| {_fmt(s.get('null_rate'))} | {_fmt(s.get('min', s.get('min_date')))} "
                f"| {_fmt(s.get('max', s.get('max_date')))} | {_fmt(s.get('avg'))} |"
            )
        else:
            lines.append(
                f"| {name} | {role} | {dtype} | {calc} | {f.get('isHidden')} | {f.get('folderName') or ''} |"
            )

    calc_fields = [f for f in fields if f.get("isCalculated") and f.get("formula")]
    if calc_fields:
        lines.append("")
        lines.append("## Calculated Field Formulas")
        lines.append("")
        for f in calc_fields:
            lines.append(f"### {f.get('name')}")
            lines.append("")
            lines.append("```")
            lines.append((f.get("formula") or "").strip())
            lines.append("```")
            lines.append("")

    if (profile.get("stats") or {}).get("note"):
        lines.append(f"> {profile['stats']['note']}")
        lines.append("")
    lines.append(
        "> Value stats reflect only rows the PAT user is permitted to see (Tableau RLS). "
        "Use a Site Administrator PAT for complete data."
    )
    return "\n".join(lines)


def _fmt(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


# --------------------------------------------------------------------------------------
# Dry run
# --------------------------------------------------------------------------------------
def do_dry_run(args: argparse.Namespace, server: str, site: str, rest_version: str) -> str:
    luid = args.datasource_luid or "<resolved-luid>"
    out: List[str] = []
    out.append("# DRY RUN — no network calls will be made\n")
    out.append("## 1. Sign in (REST)")
    out.append(f"POST {server}/api/{rest_version}/auth/signin")
    if getattr(args, "auth", "pat") == "jwt":
        out.append("# Connected App (Direct Trust) JWT. Header {alg:HS256, kid:<secret-id>, "
                   "iss:<client-id>}; claims {aud:'tableau', sub:<username>, scp:[...], "
                   "iss:<client-id>, exp, jti}. Signed (HS256) with the connected app secret value.")
        out.append(json.dumps(
            {"credentials": {"jwt": "<signed-jwt>", "site": {"contentUrl": site}}}, indent=2))
    else:
        out.append(json.dumps(
            {"credentials": {"site": {"contentUrl": site}, "personalAccessTokenName": "<PAT_NAME>",
                             "personalAccessTokenSecret": "<PAT_VALUE>"}}, indent=2))
    if not args.datasource_luid:
        out.append("\n## 2. Resolve datasource LUID (REST)")
        out.append(f"GET {server}/api/{rest_version}/sites/<site-id>/datasources"
                   f"?filter=name:eq:{args.datasource_name}")
    out.append("\n## 3. Schema profile (Metadata API GraphQL)")
    out.append(f"POST {server}/api/metadata/graphql")
    out.append(json.dumps({"query": SCHEMA_GRAPHQL,
                           "variables": {"luid": luid, "first": args.page_size, "after": None}}, indent=2))
    if args.with_stats:
        out.append("\n## 4. Value stats (VizQL Data Service) — batched")
        out.append(f"POST {server}/api/v1/vizql-data-service/read-metadata")
        out.append(json.dumps({"datasource": {"datasourceLuid": luid}}, indent=2))
        out.append("Then batched POST .../query-datasource calls, one aggregate function per "
                   "query (VDS forbids repeating a field in a single query): per-field COUNT "
                   "(non-null -> null rates), dimension COUNTD (cardinality), numeric MIN, MAX, "
                   "AVG, and date MIN, MAX. Bin/group/set fields are excluded up front; any "
                   "batch that 400s or returns multiple rows (a field acting as GROUP BY) is "
                   "split and retried so one bad field doesn't sink the batch. Example numeric "
                   "MIN batch:")
        example = {
            "datasource": {"datasourceLuid": luid},
            "query": {"fields": [
                {"fieldCaption": "Sales", "function": "MIN", "fieldAlias": "a0"},
                {"fieldCaption": "Profit", "function": "MIN", "fieldAlias": "a1"},
            ]},
        }
        out.append(json.dumps(example, indent=2))
    out.append("\n## 5. Sign out (REST)")
    out.append(f"POST {server}/api/{rest_version}/auth/signout")
    return "\n".join(out)


# --------------------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------------------
def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Profile a published Tableau datasource (schema via Metadata API; "
                    "optional value stats via VizQL Data Service).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    target = p.add_mutually_exclusive_group(required=True)
    target.add_argument("--datasource-name", help="Published datasource name (resolved to LUID via REST).")
    target.add_argument("--datasource-luid", help="Published datasource LUID (skips name resolution).")
    p.add_argument("--with-stats", action="store_true",
                   help="Also compute value-level stats via VDS (rate-limited; batched).")
    p.add_argument("--format", choices=["md", "json"], default="md", help="Output format (default: md).")
    p.add_argument("--out", help="Write output to this file instead of stdout.")
    p.add_argument("--dry-run", action="store_true",
                   help="Print the requests that would be sent; make no network calls.")
    p.add_argument("--page-size", type=int, default=200, help="GraphQL fieldsConnection page size (default 200).")
    p.add_argument("--max-fields-per-query", type=int, default=100,
                   help="Max fields per VDS query before chunking (default 100).")
    p.add_argument("--auth", choices=["pat", "jwt"], default=os.environ.get("TABLEAU_AUTH", "pat"),
                   help="Auth mode: 'pat' (default) or 'jwt' (Connected App Direct Trust).")
    p.add_argument("--jwt-username",
                   help="User to act as for JWT auth (overrides TABLEAU_JWT_USERNAME). "
                        "Use a Site Admin to bypass RLS partial-data.")
    p.add_argument("--rest-version", default=os.environ.get("TABLEAU_REST_VERSION", DEFAULT_REST_VERSION),
                   help=f"Tableau REST API version (default {DEFAULT_REST_VERSION}).")
    return p.parse_args(argv)


def _jwt_scopes_from_env() -> Optional[List[str]]:
    raw = os.environ.get("TABLEAU_JWT_SCOPES", "").strip()
    if not raw:
        return None
    parts = [s.strip() for s in raw.replace(",", " ").split()]
    return [s for s in parts if s] or None


def connect_from_env(
    rest_version: str, auth: str = "pat", jwt_username: Optional[str] = None
) -> "TableauClient":
    """Build and sign in a TableauClient using environment variables.

    Shared by the profiler and the query tool (and a future MCP server). Raises
    TableauError listing any missing variables. `auth` is 'pat' (default) or 'jwt'.
    """
    _require_requests()
    server = os.environ.get("TABLEAU_SERVER", "")
    site = os.environ.get("TABLEAU_SITE", "")
    auth = (auth or "pat").lower()
    if not server:
        raise TableauError("missing required env var: TABLEAU_SERVER")
    client = TableauClient(server, site, rest_version)
    if auth == "jwt":
        cid = os.environ.get("TABLEAU_CONNECTED_APP_CLIENT_ID", "")
        sid = os.environ.get("TABLEAU_CONNECTED_APP_SECRET_ID", "")
        sval = os.environ.get("TABLEAU_CONNECTED_APP_SECRET_VALUE", "")
        user = jwt_username or os.environ.get("TABLEAU_JWT_USERNAME", "")
        missing = [n for n, v in [
            ("TABLEAU_CONNECTED_APP_CLIENT_ID", cid),
            ("TABLEAU_CONNECTED_APP_SECRET_ID", sid),
            ("TABLEAU_CONNECTED_APP_SECRET_VALUE", sval),
            ("TABLEAU_JWT_USERNAME (or --jwt-username)", user),
        ] if not v]
        if missing:
            raise TableauError(f"missing required env var(s): {', '.join(missing)}")
        override = _jwt_scopes_from_env()
        if override is not None:
            # Operator pinned an explicit scope set; respect it verbatim.
            client.sign_in_jwt(cid, sid, sval, user, override)
            client.pulse_scopes_granted = all(s in override for s in PULSE_JWT_SCOPES)
        else:
            # Try core + Pulse; if the site rejects the Pulse scopes, fall back to core
            # so the datasource tools still work (Pulse tools then report unavailable).
            try:
                client.sign_in_jwt(cid, sid, sval, user, DEFAULT_JWT_SCOPES)
                client.pulse_scopes_granted = True
            except TableauError:
                client.sign_in_jwt(cid, sid, sval, user, CORE_JWT_SCOPES)
                client.pulse_scopes_granted = False
    else:
        pat_name = os.environ.get("TABLEAU_PAT_NAME", "")
        pat_value = os.environ.get("TABLEAU_PAT_VALUE", "")
        missing = [n for n, v in [
            ("TABLEAU_PAT_NAME", pat_name), ("TABLEAU_PAT_VALUE", pat_value),
        ] if not v]
        if missing:
            raise TableauError(f"missing required env var(s): {', '.join(missing)}")
        client.sign_in(pat_name, pat_value)
    return client


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    args.auth = (args.auth or "pat").lower()

    server = os.environ.get("TABLEAU_SERVER", "")
    site = os.environ.get("TABLEAU_SITE", "")
    pat_name = os.environ.get("TABLEAU_PAT_NAME", "")
    pat_value = os.environ.get("TABLEAU_PAT_VALUE", "")

    # Connected App (Direct Trust) JWT auth inputs.
    ca_client_id = os.environ.get("TABLEAU_CONNECTED_APP_CLIENT_ID", "")
    ca_secret_id = os.environ.get("TABLEAU_CONNECTED_APP_SECRET_ID", "")
    ca_secret_value = os.environ.get("TABLEAU_CONNECTED_APP_SECRET_VALUE", "")
    jwt_username = args.jwt_username or os.environ.get("TABLEAU_JWT_USERNAME", "")
    jwt_scopes = _jwt_scopes_from_env()

    if args.dry_run:
        text = do_dry_run(args, server or "https://<your-tableau-server>", site, args.rest_version)
        _emit(text, args.out)
        return 0

    if args.auth == "jwt":
        if jwt_scopes is not None:
            required_scopes = {"tableau:content:read"}
            if args.with_stats:
                required_scopes.add("tableau:viz_data_service:read")
            missing_scopes = sorted(required_scopes - set(jwt_scopes))
            if missing_scopes:
                sys.stderr.write(
                    "WARNING: TABLEAU_JWT_SCOPES is missing recommended scope(s): "
                    f"{', '.join(missing_scopes)}. Sign-in may succeed but content or "
                    "value-stats calls could fail.\n"
                )
        required = [
            ("TABLEAU_SERVER", server),
            ("TABLEAU_CONNECTED_APP_CLIENT_ID", ca_client_id),
            ("TABLEAU_CONNECTED_APP_SECRET_ID", ca_secret_id),
            ("TABLEAU_CONNECTED_APP_SECRET_VALUE", ca_secret_value),
            ("TABLEAU_JWT_USERNAME (or --jwt-username)", jwt_username),
        ]
    else:
        required = [
            ("TABLEAU_SERVER", server),
            ("TABLEAU_PAT_NAME", pat_name),
            ("TABLEAU_PAT_VALUE", pat_value),
        ]
    missing = [n for n, v in required if not v]
    if missing:
        sys.stderr.write(f"ERROR: missing required env var(s): {', '.join(missing)}\n")
        return 2

    client = TableauClient(server, site, args.rest_version)
    try:
        if args.auth == "jwt":
            client.sign_in_jwt(ca_client_id, ca_secret_id, ca_secret_value, jwt_username, jwt_scopes)
        else:
            client.sign_in(pat_name, pat_value)

        if args.datasource_luid:
            luid, ds_name = args.datasource_luid, None
        else:
            luid, ds_name = client.resolve_datasource_luid(args.datasource_name)

        schema = build_schema_profile(client, luid, args.page_size)
        if ds_name and not schema["header"].get("name"):
            schema["header"]["name"] = ds_name

        profile: Dict[str, Any] = {"schema": schema}

        if args.with_stats:
            try:
                stats = run_vds_stats(client, luid, args.max_fields_per_query)
            except VDSRateLimit as exc:
                stats = {
                    "fields": {},
                    "note": f"{exc} Showing schema profile only; retry value stats later.",
                }
            if stats is None:
                profile["stats"] = {
                    "note": "VizQL Data Service is disabled or unavailable for this datasource "
                            "(requires Tableau 2025.1+ with VDS enabled). Schema profile only.",
                    "fields": {},
                }
            else:
                profile["stats"] = stats

        text = render_json(profile) if args.format == "json" else render_markdown(profile)
        _emit(text, args.out)
        return 0
    except TableauError as exc:
        sys.stderr.write(f"ERROR: {exc}\n")
        return 1
    finally:
        client.sign_out()


def _emit(text: str, out_path: Optional[str]) -> None:
    if out_path:
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(text)
        sys.stderr.write(f"Wrote {out_path}\n")
    else:
        sys.stdout.write(text + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
