-- seed-star.sql  (generated by _seed_star.py)
-- Derives dbo.People and dbo.Returns from the existing dbo.Orders rows so the
-- Superstore star-schema demo has referentially-consistent related tables.
--
--   Orders.[Region]   -> People.[Region]     (Region -> Regional Manager)
--   Orders.[Order ID] -> Returns.[Order ID]  (deterministic ~20% returned)
--
-- Idempotent + transactional. Never modifies dbo.Orders.

SET XACT_ABORT ON;
SET NOCOUNT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.Orders', 'U') IS NULL
        THROW 50001, 'dbo.Orders not found. Run the Orders onboarding first.', 1;
    IF COL_LENGTH('dbo.Orders', 'Order ID') IS NULL
        THROW 50002, 'dbo.Orders is missing the [Order ID] column.', 1;
    IF COL_LENGTH('dbo.Orders', 'Region') IS NULL
        THROW 50003, 'dbo.Orders is missing the [Region] column.', 1;

    ---------------------------------------------------------------------
    -- dbo.People : one row per Region present in Orders (Region -> Manager).
    ---------------------------------------------------------------------
    IF OBJECT_ID('dbo.People', 'U') IS NULL
        CREATE TABLE dbo.People (
            [Region]           NVARCHAR(100) NOT NULL
                CONSTRAINT PK_People_Region PRIMARY KEY,
            [Regional Manager] NVARCHAR(255) NOT NULL
        );

    TRUNCATE TABLE dbo.People;

    INSERT INTO dbo.People ([Region], [Regional Manager])
    SELECT r.[Region], COALESCE(m.[Manager], N'Unassigned')
    FROM (SELECT DISTINCT [Region] FROM dbo.Orders WHERE [Region] IS NOT NULL) AS r
    LEFT JOIN (VALUES
        (N'Central', N'Roxanne Rodriguez'),
        (N'East',    N'Chuck Magee'),
        (N'South',   N'Fred Suzuki'),
        (N'West',    N'Sadie Pawthorne')
    ) AS m([Region], [Manager]) ON m.[Region] = r.[Region];

    ---------------------------------------------------------------------
    -- dbo.Returns : deterministic ~20% of distinct Order IDs, all 'Yes'.
    ---------------------------------------------------------------------
    IF OBJECT_ID('dbo.Returns', 'U') IS NULL
        CREATE TABLE dbo.Returns (
            [Order ID] NVARCHAR(255) NOT NULL
                CONSTRAINT PK_Returns_OrderID PRIMARY KEY,
            [Returned] NVARCHAR(3) NOT NULL
                CONSTRAINT CK_Returns_Returned CHECK ([Returned] IN (N'Yes', N'No'))
        );

    TRUNCATE TABLE dbo.Returns;

    INSERT INTO dbo.Returns ([Order ID], [Returned])
    SELECT o.[Order ID], N'Yes'
    FROM (SELECT DISTINCT [Order ID] FROM dbo.Orders WHERE [Order ID] IS NOT NULL) AS o
    WHERE ABS(CAST(CHECKSUM(o.[Order ID]) AS BIGINT)) % 5 = 0;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;

SELECT N'People'  AS [Table], COUNT(*) AS [Rows] FROM dbo.People
UNION ALL
SELECT N'Returns' AS [Table], COUNT(*)          FROM dbo.Returns;
